FROM ruby:2.5

RUN gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/
RUN gem sources -l
RUN gem install bcrypt:3.1.12 chronic:0.10.2 timers:4.3.0 rspec:3.6.0 pry-rescue awesome_print pry --no-doc

# RUN useradd -ms /bin/bash coderlane

# USER coderlane

# WORKDIR /home/coderlane/workspace

CMD bash -c "if [ $runType == 'execute' ]; then script -q -c 'ruby Main.rb 2>&1' coderlane.log; elif [ $runType == 'code' ]; then irb --noecho; fi"
