FROM python:2.7.16

RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ numpy scipy pandas requests beautifulsoup4 ipython==5.8.0

# RUN useradd -ms /bin/bash coderlane

# USER coderlane

# WORKDIR /home/coderlane/workspace

RUN ipython profile create

CMD bash -c "if [ $runType == 'execute' ]; then script -q -c 'python Main.py 2>&1' coderlane.log; elif [ $runType == 'code' ]; then python; fi"
